# src/visualization/dashboard.py
import streamlit as st
import os
import numpy as np
import pandas as pd
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
import glob
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(layout="wide", page_title="ACL Dashboard")

def load_scalars_from_run(run_dir):
    # find event files
    event_files = glob.glob(os.path.join(run_dir, "events.*"))
    if not event_files:
        return None
    ea = EventAccumulator(run_dir, size_guidance={'scalars': 0})
    ea.Reload()
    tags = ea.Tags().get('scalars', [])
    data = {}
    for tag in tags:
        events = ea.Scalars(tag)
        steps = [e.step for e in events]
        vals = [e.value for e in events]
        data[tag] = pd.DataFrame({"step": steps, "value": vals})
    return data

st.title("Adaptive Curriculum Learning — Dashboard")

runs = [d for d in os.listdir("runs") if os.path.isdir(os.path.join("runs", d))]
run_sel = st.selectbox("Select run folder", [""] + runs)

if run_sel:
    run_path = os.path.join("runs", run_sel)
    st.write("Run:", run_path)
    st.write("Loading TensorBoard scalars...")
    data = load_scalars_from_run(run_path)
    if not data:
        st.warning("No tensorboard events found in run. Try selecting a run generated by experiments.")
    else:
        st.sidebar.markdown("**Available Scalars**")
        tags = list(data.keys())
        selected_tags = st.sidebar.multiselect("Show scalars", tags[:6], default=tags[:4])
        cols = st.columns(2)
        for t in selected_tags:
            df = data[t]
            ax = df.plot(x="step", y="value", title=t, legend=False)
            st.pyplot(ax.get_figure())
            plt.clf()

        if "difficulty/all_scores" in data:
            st.subheader("Difficulty distribution (latest)")
            df = data["difficulty/all_scores"]
            # take last reported histogram-ish values (we logged arrays as histograms but EventAccumulator returns scalars)
            # fallback: load final_results.json
            res_file = os.path.join(run_path, "final_results.json")
            if os.path.exists(res_file):
                import json
                with open(res_file, "r") as f:
                    jd = json.load(f)
                    scores = [it.get("difficulty_score", 0.0) for it in jd.get("items",[])]
                    st.write("Items:", len(scores))
                    fig, ax = plt.subplots()
                    sns.histplot(scores, bins=30, ax=ax)
                    st.pyplot(fig)
            else:
                st.write("No final_results.json found; histogram unavailable.")
